### ISSUE TITLE
Bad colors

### ISSUE THREAD

**Issue by WoH** [ParanoidAndroid/android_build#2]
One of the commits added on February 24 breaks the colors for bravo.
Before: http://i49.tinypic.com/6j2ivr.png
After: http://i45.tinypic.com/161hwd2.png

**Comment by aaronpoweruser** [comment]
that looks bad, weird how the icons look fine though, try doing  a clean build with no cache, also what processor

**Comment by WoH** [comment]
Solved, this probably occured because I forgot to remove some traces of my vodoo with the camera.
